### ISSUE TITLE
Lights don't function after apt-get dist-upgrade 

### ISSUE THREAD

**Issue by flyflytn** [jasaw/build-lights#1]
Hi J,
I did a dist-upgrade, and after a reboot the build lights don't light up at all. All other functionality is correct, it gets msgs off SQS and plays sounds for events etc.
(trevor @ poste haste)

**Comment by flyflytn** [comment]
The output from python test.py is:
Fill LEDs
Strand: LED driver thread: STARTED
LED join

and then it just stays in the loop forever, without any reported error (ie. if not led.isAlive() does not break out, so its like everything is OK, but no lights are lit)

**Comment by jasaw** [comment]
Most likely your OS stopped loading the spi-bcm2708 driver after the dist-upgrade.
Try either re-enabling the SPI driver from raspi-config or manually adding it to /etc/modules file.

**Comment by flyflytn** [comment]
OK. I did check that, and saw /dev/spidev0.0 so assumed it was OK. Also /etc/modules had the bcm module in there for spi-bcm2708.
After your suggestion, I tried raspi-config, and after configuring through it, it created /dev/spi-dev0.1 in addition to /dev/spi-dev0.0, and now the lights work. Strange.
